name: Deploy to EC2

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up SSH key and whitelist EC2 IP address
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy ssh file to remote server
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          scp -r ~/.ssh/id_rsa ./deploy.sh $EC2_USERNAME@$EC2_HOST:/home/ubuntu/

      - name: Run Bash Script To Delpoy App
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST "chmod +x ./deploy.sh && ./deploy.sh"

      - name: Clean up SSH key
        if: always()
        run: rm -f ~/.ssh/id_rsa

  test-deployment:
    needs: deploy
    name: Test deployment
    runs-on: ubuntu-latest

    steps:
      - name: Run test script
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: node test_deployment.js http://$EC2_HOST
